postgresql:
  image: postgres:9.4.1
redis:
  image: redis:3.0.1
web:
  build: .
  command: bin/rails server
  links:
   - postgresql
   - redis
  ports:
   - "3000:3000"
  environment:
    POSTGRESQL_USER: postgres
