postgres:
  image: postgres:9.4.5
redis:
  image: redis:3.0.5
workers:
  image: brewformulasorg_web
  command: sidekiq
  links:
    - postgres:postgres
    - redis:redis
  environment:
    - POSTGRESQL_USER=postgres
    - RUNNING_IN_DOCKER=true
bundle:
  image: brewformulasorg_web
  command: echo Bundler data container
  volumes:
    - /bundle
web:
  build: .
  command: bin/rails server -b 0.0.0.0
  links:
   - postgres
   - redis
  ports:
   - "3000:3000"
  environment:
    - POSTGRESQL_USER=postgres
    - RAILS_ENV=development
    - VIRTUAL_HOST=localhost:3000
  volumes:
    - .:/application/
  volumes_from:
    - bundle
