postgresql:
  image: postgres:9.4.1
redis:
  image: redis:3.0.1
web:
  build: .
  command: bin/rails server -b 0.0.0.0
  links:
   - postgresql
   - redis
  ports:
   - "3000:3000"
  environment:
    - POSTGRESQL_USER=postgres
    - RAILS_ENV=development
  volumes:
    - .:/brewformulas/application/
