postgresql: &postgresql
  adapter: postgresql
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] || ENV['BREWFORMULASORG_POSTGRESQL_1_PORT_5432_TCP_ADDR'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] || ENV['BREWFORMULASORG_POSTGRESQL_1_PORT_5432_TCP_PORT'] || 5432 %>
  username: <%= ENV['POSTGRESQL_USER'] || 'brewformulas' %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  template: <%= ENV['POSTGRESQL_TEMPLATE'] || 'template0' %>
  database: brewformulas_org
  min_messages: ERROR

defaults: &defaults
  <<: *postgresql
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  database: brewformulas_org_dev

test:
  <<: *defaults
  database: brewformulas_org_test

cucumber:
  <<: *defaults
  database: brewformulas_org_test

production:
  <<: *defaults
  pool: 10
  database: brewformulas_org_prod
