postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: brewformulas_org_test
  min_messages: ERROR
  template: template0

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>

test:
  <<: *defaults

cucumber:
  <<: *defaults
